(()=>{'use strict';

const ENGINE_NAME='Composition Engine';
const ENGINE_VERSION='2.13.0';

const COMPOSITION_CONTRACT=`KOMPAKTES PARTITURFORMAT:\nH|["Titel",BPM,Zähler,Nenner]\nV|["Instrument",Program,Channel]\nB|Takt|[[Position,Dauer,Pitch,Velocity],...]\nDanach weitere B-Zeilen oder eine neue V-Zeile. Jede Zeile ist abgeschlossen. Takt beginnt bei 1; Position und Dauer in Viertelnoten-Einheiten. Pausen sind Lücken. Notennamen werden nicht zusätzlich ausgegeben.`
const TECHNICAL_CONTRACT=COMPOSITION_CONTRACT;
const REPRESENTATION_CONTRACTS=Object.freeze({
 compact:COMPOSITION_CONTRACT,
 abc:`ABC-NOTATION:
Gib ausschließlich vollständige, gültige ABC-Notation aus. Verwende X:, T:, M:, L:, Q: und K:. Mehrstimmigkeit mit V:-Stimmen. Benenne Instrumente in den V:-Definitionen eindeutig und verwende bei Bedarf %%score/%%staves. Nutze musikalisch sinnvolle Dynamik (!pp! bis !fff!, Akzente, Crescendo/Diminuendo), Artikulation, Bindebögen, Phrasierung und spieltechnische Anweisungen, wenn sie zum Ausdruck der Komposition beitragen. Keine Erklärung außerhalb der ABC-Notation.`,
 midi:`MIDI-PERFORMANCE-TEXT (960 PPQ):
H|["Titel",BPM,Zähler,Nenner]
V|["Instrument",Program,Channel]
N|StartTick|DauerTicks|Pitch|Velocity
Optional: C|Tick|Controller|Wert
Danach weitere N-/C-Zeilen oder eine neue V-Zeile. StartTick und Dauer sind frei auf 960 Ticks pro Viertelnote aufgelöst; keine Quantisierung auf Notenwerte.`,
 free:`TECHNISCHES AUSGABEPAKET — LILYPOND + MIDI:
Die musikalische Fassung ist bereits fertig komponiert. Übertrage sie NICHT neu, sondern korrigiere nur technische Notationsfehler und realisiere sie vollständig.

Beginne exakt mit:
FORMAT|LILYPOND+MIDI
LILYPOND
Danach vollständiger, kompilierbarer LilyPond-Quelltext. Verwende \version "2.24.0". Prüfe insbesondere Taktfüllung, Stimmen, Bindungen, Dynamik, Instrumentenregister und bei \relative-Notation jede Oktavmarkierung. Extreme Register dürfen nur erhalten bleiben, wenn sie aus der musikalischen Vorlage eindeutig beabsichtigt sind; korrigiere offensichtlich technische Oktavfehler ohne die Musik neu zu komponieren.
Danach eine eigene Zeile:
MIDI
Danach MIDI-PERFORMANCE-TEXT mit H|, V| und N|StartTick|DauerTicks|Pitch|Velocity, optional C|Tick|Controller|Wert, T|Tick|BPM und P|Tick|Wert; 960 PPQ. MIDI muss exakt dieselbe Musik wie die LilyPond-Fassung wiedergeben.
Keine Erklärung außerhalb dieser beiden Blöcke.`
});
function representationOf(snapshot){const r=String(snapshot?.representation||'compact').toLowerCase();return REPRESENTATION_CONTRACTS[r]?r:'compact'}
function createPrompts(snapshot,composition=''){
 const representation=representationOf(snapshot),contract=REPRESENTATION_CONTRACTS[representation];
 return{
  composition:'AUFTRAG:\n'+snapshot.visibleTask+'\n\nKomponiere das Werk jetzt vollständig als Musik. Triff alle musikalischen Entscheidungen frei nach dem Auftrag. Gib die vollständig auskomponierte musikalische Fassung in der musikalischen Darstellung aus, die dir für das Komponieren selbst am natürlichsten ist.',
  realization:'Übertrage die folgende bereits vollständig komponierte Musik so getreu wie möglich in das verlangte technische Ausgabeformat. Komponiere NICHT neu. Vereinfache, regularisiere oder verschönere die Musik NICHT. Erhalte insbesondere Tonhöhen, Rhythmen, Pausen, Stimmen, Phrasierung, Dynamik, Artikulation, Verzierungen, Tempo- und Ausdrucksangaben, soweit das Zielformat sie darstellen kann. Wenn etwas nicht direkt darstellbar ist, bewahre die musikalische Bedeutung so vollständig wie möglich.\\n\\nBEREITS FERTIG KOMPONIERTE MUSIK:\\n'+composition+'\\n\\nTECHNISCHES ZIELFORMAT:\\n'+contract,
  compositionIdea:'Beschreibe die bereits fertig komponierte Partitur konkret, differenziert und hörbezogen. Erfasse nur Eigenschaften, die aus der tatsächlichen Partitur hervorgehen. Etwa 500 bis 900 Zeichen, höchstens 900 Zeichen. Keine Bewertung, keine Verbesserungsvorschläge und keine Wiederholung des Auftrags.\\n\\nFERTIGE PARTITUR:\\n'+composition
 };
}
function criticalAnalysisPrompt(score){return 'Beurteile diese Partitur als musikalisches Werk. Suche nicht zwanghaft nach Fehlern. Frage zuerst, ob die Komposition in ihrem Charakter, Verlauf, ihrer Phrasierung, Rhythmik, Harmonik, Textur, Spannung und Entwicklung musikalisch überzeugt. Nenne nur dann ÄNDERN, wenn eine wesentliche musikalische Schwäche vorliegt und eine Änderung einen klaren hörbaren Gewinn verspricht. Kleine technische Auffälligkeiten, einzelne Notenlücken, Überlappungen oder MIDI-Dauern sind NICHT Gegenstand dieser musikalischen Analyse und dürfen allein kein ÄNDERN begründen. Beginne genau mit "URTEIL: ÄNDERN" oder "URTEIL: BEHALTEN". Danach höchstens 220 Zeichen: bei ÄNDERN die eine wichtigste musikalische Schwäche und eine knappe musikalische Verbesserung; bei BEHALTEN ein knapper Grund. Keine Lobhudelei, keine technische Fehlerliste, keine Takt-für-Takt-Abhandlung.\\n\\nPARTITUR:\\n'+JSON.stringify(scoreToCompact(score))+'\\n\\nFORMAT:\\n'+TECHNICAL_CONTRACT}
function conciseAssessment(value){
 const raw=String(value||'').trim().replace(/\r/g,'');
 const m=raw.match(/^\s*URTEIL:\s*(ÄNDERN|BEHALTEN)\b\s*([\s\S]*)$/i);
 if(!m)return raw.slice(0,220);
 const verdict='URTEIL: '+m[1].toUpperCase();
 const reason=m[2].replace(/^\s*[:\-–—]?\s*/,'').replace(/\s+/g,' ').trim();
 return reason?verdict+'\n'+reason.slice(0,220):verdict;
}
function approvedImprovementPrompt(score,assessment){return 'Überarbeite die vorhandene Partitur musikalisch mit voller kompositorischer Sorgfalt. Beseitige die im freigegebenen Urteil diagnostizierten hörbaren Ursachen tatsächlich. Priorität haben Fluss und Phrasierung: ungewollte Minipausen, Lücken, zu kurze Dauern, fehlende Bindung, abgehackte Übergänge oder mechanisches Stolpern müssen in den konkreten Startzeiten und Dauern korrigiert werden, soweit sie nicht musikalisch beabsichtigt sind. Prüfe die geänderten Passagen als zusammenhängenden zeitlichen Verlauf. Bewahre überzeugende Eigenschaften und ändere nichts ohne musikalischen Grund. Antworte ausschließlich mit der vollständigen Partitur im kompakten JSON-Format.\\n\\nFREIGEGEBENES URTEIL:\\n'+String(assessment||'').trim()+'\\n\\nPARTITUR:\\n'+JSON.stringify(scoreToCompact(score))+'\\n\\nFORMAT:\\n'+TECHNICAL_CONTRACT}
function postImprovementAnalysisPrompt(improvedScore){return 'Beurteile diese Partitur unabhängig als musikalisches Werk, ohne eine frühere Fassung vorauszusetzen. Suche nicht zwanghaft nach Fehlern. Entscheide, ob eine wesentliche musikalische Schwäche vorliegt, deren Änderung einen klaren hörbaren Gewinn verspricht. Kleine technische Auffälligkeiten, einzelne Notenlücken, Überlappungen oder MIDI-Dauern sind nicht Gegenstand dieser musikalischen Analyse. Beginne genau mit "URTEIL: ÄNDERN" oder "URTEIL: BEHALTEN". Danach höchstens 220 Zeichen: nur die wichtigste musikalische Begründung; bei ÄNDERN eine knappe musikalische Verbesserung. Keine Lobhudelei, keine technische Fehlerliste.\\n\\nPARTITUR:\\n'+JSON.stringify(scoreToCompact(improvedScore))+'\\n\\nFORMAT:\\n'+TECHNICAL_CONTRACT}
async function analyzeScore({score,snapshot,key,requestModel,run=null,event=null}){if(!score)throw new Error('Keine Partitur für die Analyse.');if(typeof requestModel!=='function')throw new Error('requestModel fehlt.');const promptText=criticalAnalysisPrompt(score),text=conciseAssessment(await requestModel({snapshot,key,promptText,stage:'critical_score_analysis',run,event}));return{assessment:text,unchanged:/^\\s*URTEIL:\\s*BEHALTEN\\b/im.test(text),promptText}}
async function analyzeImprovement({improvedScore,snapshot,key,requestModel,run=null,event=null}){if(!improvedScore)throw new Error('Verbesserungsfassung fehlt.');if(typeof requestModel!=='function')throw new Error('requestModel fehlt.');const promptText=postImprovementAnalysisPrompt(improvedScore),text=conciseAssessment(await requestModel({snapshot,key,promptText,stage:'post_improvement_analysis',run,event}));return{assessment:text,unchanged:/^\\s*URTEIL:\\s*BEHALTEN\\b/im.test(text),promptText}}
function exportABC(score){if(score?.abcSource)return String(score.abcSource).trim();return''}
function exportLilyPond(score){if(score?.lilypondSource)return String(score.lilypondSource).trim();return''}
function exportMusicXML(score){
 if(!score)return'';const esc=x=>String(x??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');const div=960,ts=Array.isArray(score.timeSignature)?score.timeSignature:[4,4],bar=(Number(ts[0])||4)*4/(Number(ts[1])||4),pcs=[['C',0],['C',1],['D',0],['D',1],['E',0],['F',0],['F',1],['G',0],['G',1],['A',0],['A',1],['B',0]],px=m=>{m=Math.round(Number(m)||60);const x=pcs[(m%12+12)%12];return'<pitch><step>'+x[0]+'</step>'+(x[1]?'<alter>'+x[1]+'</alter>':'')+'<octave>'+(Math.floor(m/12)-1)+'</octave></pitch>'},tracks=score.tracks||[];
 let out='<?xml version="1.0" encoding="UTF-8"?><score-partwise version="4.0"><work><work-title>'+esc(score.title||'Komposition')+'</work-title></work><part-list>'+tracks.map((t,i)=>'<score-part id="P'+(i+1)+'"><part-name>'+esc(t.name||('Track '+(i+1)))+'</part-name><midi-instrument id="P'+(i+1)+'-I1"><midi-channel>'+((Number(t.channel)||i)%16+1)+'</midi-channel><midi-program>'+((Number(t.program)||0)+1)+'</midi-program></midi-instrument></score-part>').join('')+'</part-list>';
 for(let ti=0;ti<tracks.length;ti++){const tr=tracks[ti],end=(tr.notes||[]).reduce((m,n)=>Math.max(m,(Number(n[0])||0)+(Number(n[1])||0)),0),bars=Math.max(1,Math.ceil(end/bar));out+='<part id="P'+(ti+1)+'">';for(let bi=0;bi<bars;bi++){const bs=bi*bar,be=bs+bar;out+='<measure number="'+(bi+1)+'">';if(!bi)out+='<attributes><divisions>'+div+'</divisions><time><beats>'+ts[0]+'</beats><beat-type>'+ts[1]+'</beat-type></time></attributes><direction><direction-type><metronome><beat-unit>quarter</beat-unit><per-minute>'+Math.round(Number(score.bpm)||120)+'</per-minute></metronome></direction-type><sound tempo="'+Math.round(Number(score.bpm)||120)+'"/></direction>';
 const ex=(tr.expressions||[]).filter(e=>(Number(e.at)||0)>=bs&&(Number(e.at)||0)<be);for(const e of ex){if(e.type==='dynamic')out+='<direction><direction-type><dynamics><'+esc(e.mark)+'/></dynamics></direction-type></direction>';else if(e.type==='hairpin')out+='<direction><direction-type><wedge type="'+(e.phase==='stop'?'stop':e.direction==='diminuendo'?'diminuendo':'crescendo')+'"/></direction-type></direction>';else if(e.type==='direction')out+='<direction><direction-type><words>'+esc(e.text)+'</words></direction-type></direction>'}
 const ns=(tr.notes||[]).filter(n=>(Number(n[0])||0)>=bs&&(Number(n[0])||0)<be).sort((a,b)=>a[0]-b[0]);let cur=bs;for(const n of ns){const st=Number(n[0])||0,d=Math.max(.001,Number(n[1])||.25);if(st>cur+.0001)out+='<forward><duration>'+Math.round((st-cur)*div)+'</duration></forward>';const at=ex.filter(e=>Math.abs((Number(e.at)||0)-st)<.001),art=at.find(e=>e.type==='articulation'),orn=at.find(e=>e.type==='ornament'),sl=at.filter(e=>e.type==='slur'),fer=at.find(e=>e.type==='fermata');let not='';if(art||orn||sl.length||fer){not='<notations>'+(art?'<articulations><'+(art.kind==='accent'||art.kind==='marcato'?art.kind:art.kind==='staccatissimo'?'staccatissimo':art.kind==='tenuto'?'tenuto':'staccato')+'/></articulations>':'')+(orn?'<ornaments><'+(orn.kind==='trill'?'trill-mark':orn.kind)+'/></ornaments>':'')+sl.map(x=>'<slur type="'+(x.phase==='stop'?'stop':'start')+'"/>').join('')+(fer?'<fermata/>':'')+'</notations>'}out+='<note dynamics="'+Math.round((Number(n[3])||80)/127*100)+'">'+px(n[2])+'<duration>'+Math.round(d*div)+'</duration>'+not+'</note>';cur=Math.max(cur,st+d)}out+='</measure>'}out+='</part>'}return out+'</score-partwise>'}
function playbackScore(score){const out=performanceSnapshot(score);for(const tr of out.tracks){const src=tr.notes.map(n=>n.slice()),extra=[];const cc11=(tr.cc||[]).filter(c=>c[1]===11).sort((a,b)=>a[0]-b[0]),ped=(tr.cc||[]).filter(c=>c[1]===64).sort((a,b)=>a[0]-b[0]);const valueAt=(arr,t,def)=>{let v=def;for(const e of arr){if(e[0]>t)break;v=e[2]}return v};for(const n of src){n[3]=Math.max(1,Math.min(127,Math.round((Number(n[3])||80)*valueAt(cc11,n[0],127)/127)));if(valueAt(ped,n[0],0)>=64){const off=ped.find(e=>e[0]>n[0]&&e[2]<64);if(off)n[1]=Math.max(n[1],off[0]-n[0])}const ex=(tr.expressions||[]).filter(e=>Math.abs((Number(e.at)||0)-n[0])<.001);for(const e of ex){if(e.type==='grace'&&e.pitches?.length){const gd=Math.min(.12,Math.max(.04,n[1]/(e.pitches.length+4))),start=Math.max(0,n[0]-gd*e.pitches.length);e.pitches.forEach((p,i)=>extra.push([start+i*gd,gd*.9,p,Math.max(1,n[3]-8)]))}if(e.type==='ornament'&&e.kind==='trill'){const step=Math.min(.125,Math.max(.05,n[1]/8)),count=Math.max(2,Math.floor(n[1]/step));n[1]=step*.92;for(let i=1;i<count;i++)extra.push([n[0]+i*step,step*.92,n[2]+(i%2?2:0),n[3]])}if(e.type==='fermata')n[1]*=1.5}}tr.notes=src.concat(extra).sort((a,b)=>a[0]-b[0]||a[2]-b[2])}return out}
function performanceSnapshot(score){return{title:String(score?.title||''),bpm:Number(score?.bpm)||120,timeSignature:Array.isArray(score?.timeSignature)?score.timeSignature:[4,4],tempoEvents:(score?.tempoEvents||[]).map(x=>[Number(x[0])||0,Number(x[1])||120]),tracks:(score?.tracks||[]).map((tr,i)=>({name:String(tr.name||('Track '+(i+1))),program:Number(tr.program)||0,channel:Number.isFinite(Number(tr.channel))?Number(tr.channel):i,notes:(tr.notes||[]).map(n=>Array.isArray(n)?n.slice():n),cc:(tr.cc||[]).map(c=>Array.isArray(c)?c.slice():c),pitchBend:(tr.pitchBend||[]).map(p=>Array.isArray(p)?p.slice():p),expressions:(tr.expressions||[]).map(e=>({...e}))}))}}
function expressionAudit(score){const p=performanceSnapshot(score),k={notes:0,velocity:0,cc:0,pedal:0,expressionCC:0,pitchBend:0,tempo: p.tempoEvents.length,dynamics:0,hairpins:0,articulations:0,slurs:0,ornaments:0,grace:0,fermatas:0,directions:0};for(const tr of p.tracks){k.notes+=tr.notes.length;k.velocity+=tr.notes.filter(n=>Array.isArray(n)&&Number.isFinite(Number(n[3]))).length;k.cc+=tr.cc.length;k.pedal+=tr.cc.filter(c=>c[1]===64).length;k.expressionCC+=tr.cc.filter(c=>c[1]===11).length;k.pitchBend+=tr.pitchBend.length;for(const e of tr.expressions){if(e.type==='dynamic')k.dynamics++;else if(e.type==='hairpin')k.hairpins++;else if(e.type==='articulation')k.articulations++;else if(e.type==='slur')k.slurs++;else if(e.type==='ornament')k.ornaments++;else if(e.type==='grace')k.grace++;else if(e.type==='fermata')k.fermatas++;else if(e.type==='direction')k.directions++}}return k}
function scoreToCompact(score){const ts=Array.isArray(score?.timeSignature)?score.timeSignature:[4,4],beats=(Number(ts[0])||4)*(4/(Number(ts[1])||4));return{t:String(score?.title||''),b:Number(score?.bpm)||120,m:ts,v:(score?.tracks||[]).map((tr,i)=>[String(tr.name||('Track '+(i+1))),Number(tr.program)||0,Number.isFinite(Number(tr.channel))?Number(tr.channel):i,(tr.notes||[]).map(n=>{const start=Number(n?.[0])||0,bar=Math.floor(start/beats)+1,pos=start-(bar-1)*beats,row=[bar,pos,Number(n?.[1])||.25,Number(n?.[2])||60,Number(n?.[3])||80];if(typeof n?.[4]==='string'&&n[4])row.push(n[4]);return row})])}}
async function improveScore({score,assessment,snapshot,key,requestModel,run=null,event=null}){if(!score||!String(assessment||'').trim())throw new Error('Partitur oder Verbesserungsvorschlag fehlt.');if(typeof requestModel!=='function')throw new Error('requestModel fehlt.');const promptText=approvedImprovementPrompt(score,assessment),text=String(await requestModel({snapshot,key,promptText,stage:'approved_score_improvement',run,event})||'').trim(),obj=extractJson(text),improvedScore=findScore(obj);return{score:improvedScore,midiBytes:buildMidi(improvedScore),raw:text,promptText}}

function mergeTitleRegistry(savedTitles,activeTitles){const seen=new Set(),result=[];for(const value of [...(savedTitles||[]),...(activeTitles||[])]){const t=String(value||'').trim(),key=t.toLocaleLowerCase('de-DE');if(t&&!seen.has(key)){seen.add(key);result.push(t)}}return result}
function duplicateTitlePrompt(title,allTitles,draft){const hint=String(draft||'').slice(0,700);return'Erfinde ausschließlich einen neuen kurzen Werktitel für die bereits fertige Komposition. Keine musikalische Änderung. Antworte nur mit dem Titel.\n\nBISHERIGER TITEL:\n'+title+'\n\nBEREITS VERWENDET:\n'+allTitles.join('\n')+'\n\nKURZER KONTEXT:\n'+hint}
function makeRequest(p,m,promptText,stage){if(p==='openai')return{provider:p,model:m,url:'https://api.openai.com/v1/responses',method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer {{API_KEY}}'},body:{model:m,input:[{role:'user',content:[{type:'input_text',text:promptText}]}],store:false}};if(p==='anthropic'){const body={model:m,max_tokens:32768,messages:[{role:'user',content:promptText}]};return{provider:p,model:m,url:'https://api.anthropic.com/v1/messages',method:'POST',headers:{'Content-Type':'application/json','x-api-key':'{{API_KEY}}','anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body};}const body={contents:[{role:'user',parts:[{text:promptText}]}]};if(/^gemini-3\./i.test(m)&&stage==='composition_idea_afterwards')body.generationConfig={thinkingConfig:{thinkingLevel:'low'}};return{provider:p,model:m,url:`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(m)}:generateContent?key={{API_KEY}}`,method:'POST',headers:{'Content-Type':'application/json'},body}}
function actualRequest(s,key){const headers={...s.headers};let url=s.url;for(const k of Object.keys(headers)){if(typeof headers[k]==='string'&&headers[k].includes('{{API_KEY}}'))headers[k]=headers[k].replace('{{API_KEY}}',key)}url=url.replace('{{API_KEY}}',encodeURIComponent(key));return{url,headers,body:structuredClone(s.body)}}
function extractText(p,j){if(p==='openai'){if(typeof j.output_text==='string')return j.output_text;const parts=[];for(const item of(j.output||[]))for(const c of(item.content||[]))if(typeof c.text==='string')parts.push(c.text);return parts.join('\n')}if(p==='anthropic')return(j.content||[]).filter(x=>x.type==='text').map(x=>x.text||'').join('\n');return(j.candidates||[]).flatMap(c=>c.content?.parts||[]).map(p=>p.text||'').join('\n')}
function normalizeJsonNumbers(s){let out='',quoted=false,escaped=false;for(let i=0;i<s.length;i++){const c=s[i];if(quoted){out+=c;if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')quoted=false;continue}if(c==='"'){quoted=true;out+=c;continue}if(c==='.'&&/[0-9]/.test(s[i+1]||'')&&(/[\[:,\[]/.test(s.slice(0,i).trimEnd().slice(-1))||(/[\[:,\[]/.test(s.slice(0,i).trimEnd().slice(-2,-1))&&s[i-1]==='-'))){out+='0'+c;continue}out+=c}return out}
function closeCompleteScoreJson(s){if(!s.endsWith('}'))return null;let stack=[],quoted=false,escaped=false;for(let i=0;i<s.length;i++){const c=s[i];if(quoted){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')quoted=false;continue}if(c==='"'){quoted=true;continue}if(c==='{'||c==='['){stack.push(c);continue}if(c==='}'||c===']'){const top=stack[stack.length-1];if((top==='{'&&c==='}')||(top==='['&&c===']')){stack.pop();continue}if(i===s.length-1&&c==='}'&&top==='['&&stack[0]==='{'&&stack.slice(1).every(x=>x==='[')){const candidate=s.slice(0,-1)+']'.repeat(stack.length-1)+'}';try{const obj=JSON.parse(normalizeJsonNumbers(candidate));if(Array.isArray(obj.v)&&obj.v.length>0&&obj.v.every(v=>Array.isArray(v)&&Array.isArray(v[3])&&v[3].length>0))return candidate}catch(_){} }return null}}return null}
function extractCompactScore(text){
 const lines=String(text||'').trim().split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
 let head=null,current=null,tracks=[];
 for(const line of lines){
  if(line.startsWith('H|')){const h=JSON.parse(line.slice(2));if(!Array.isArray(h)||h.length<4)throw new Error('Ungültige H-Zeile.');head=h;continue}
  if(line.startsWith('V|')){const v=JSON.parse(line.slice(2));if(!Array.isArray(v)||v.length<3)throw new Error('Ungültige V-Zeile.');current={name:String(v[0]||('Track '+(tracks.length+1))),program:Number(v[1])||0,channel:Number.isFinite(Number(v[2]))?Number(v[2]):tracks.length,notes:[]};tracks.push(current);continue}
  if(line.startsWith('B|')){if(!current)throw new Error('B-Zeile ohne V-Zeile.');const p=line.indexOf('|',2),bar=Number(line.slice(2,p)),events=JSON.parse(line.slice(p+1));if(!Number.isInteger(bar)||bar<1||!Array.isArray(events))throw new Error('Ungültige B-Zeile.');current._bars=current._bars||[];current._bars.push([bar,events]);continue}
  throw new Error('Unbekannte Partiturzeile.');
 }
 if(!head||!tracks.length)throw new Error('Unvollständiges kompaktes Partiturformat.');
 const ts=[Number(head[2])||4,Number(head[3])||4],beats=ts[0]*(4/ts[1]);
 for(const tr of tracks){for(const [bar,events] of(tr._bars||[]))for(const e of events){if(!Array.isArray(e)||e.length<4)throw new Error('Ungültiges Notenereignis.');const pos=Number(e[0]),du=Number(e[1]),pi=Number(e[2]),ve=Number(e[3]);if(!Number.isFinite(pos)||pos<0||!Number.isFinite(du)||du<=0||!Number.isInteger(pi)||pi<0||pi>127||!Number.isInteger(ve)||ve<1||ve>127)throw new Error('Ungültiges Notenereignis.');tr.notes.push([(bar-1)*beats+pos,du,pi,ve])}delete tr._bars}
 return{title:String(head[0]||''),bpm:Number(head[1])||120,timeSignature:ts,tracks};
}
function extractMidiPerformanceScore(text){
 const lines=String(text||'').trim().split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let head=null,current=null,tracks=[],tempoEvents=[];
 for(let i=0;i<lines.length;i++){const line=lines[i];
  if(/^(#|;|\/\/)/.test(line)||/^\`\`\`/.test(line))continue;
  if(line.startsWith('H|')){head=JSON.parse(line.slice(2));continue}
  if(line.startsWith('V|')){const v=JSON.parse(line.slice(2));current={name:String(v[0]||('Track '+(tracks.length+1))),program:Number(v[1])||0,channel:Number.isFinite(Number(v[2]))?Number(v[2]):tracks.length,notes:[],cc:[],pitchBend:[]};tracks.push(current);continue}
  if(line.startsWith('N|')){if(!current)throw new Error('N-Zeile ohne V-Zeile.');const p=line.split('|').slice(1).map(Number);if(p.length<4||p.some(x=>!Number.isFinite(x)))throw new Error('Ungültige N-Zeile in Zeile '+(i+1)+'.');current.notes.push([p[0]/960,p[1]/960,Math.round(p[2]),Math.round(p[3])]);continue}
  if(line.startsWith('C|')){if(!current)throw new Error('C-Zeile ohne V-Zeile.');const p=line.split('|').slice(1).map(Number);if(p.length<3||p.some(x=>!Number.isFinite(x)))throw new Error('Ungültige C-Zeile in Zeile '+(i+1)+'.');current.cc.push([p[0]/960,Math.round(p[1]),Math.round(p[2])]);continue}
  if(line.startsWith('T|')){const p=line.split('|').slice(1).map(Number);if(p.length<2||p.some(x=>!Number.isFinite(x)))throw new Error('Ungültige T-Zeile in Zeile '+(i+1)+'.');tempoEvents.push([p[0]/960,p[1]]);continue}
  if(line.startsWith('P|')){if(!current)throw new Error('P-Zeile ohne V-Zeile.');const p=line.split('|').slice(1).map(Number);if(p.length<2||p.some(x=>!Number.isFinite(x)))throw new Error('Ungültige P-Zeile in Zeile '+(i+1)+'.');current.pitchBend.push([p[0]/960,Math.max(-8192,Math.min(8191,Math.round(p[1])))]);continue}
  throw new Error('Unbekannte MIDI-Performance-Zeile '+(i+1)+': '+line.slice(0,120));
 }
 if(!Array.isArray(head)||head.length<4||!tracks.length)throw new Error('Unvollständiges MIDI-Performance-Format.');
 return{title:String(head[0]||''),bpm:Number(head[1])||120,timeSignature:[Number(head[2])||4,Number(head[3])||4],tracks,tempoEvents};
}
const SEMI={C:0,D:2,E:4,F:5,G:7,A:9,B:11};
const KEYS={C:[],G:['F'],D:['F','C'],A:['F','C','G'],E:['F','C','G','D'],B:['F','C','G','D','A'],'F#':['F','C','G','D','A','E'],'C#':['F','C','G','D','A','E','B'],F:['B'],'Bb':['B','E'],'Eb':['B','E','A'],'Ab':['B','E','A','D'],'Db':['B','E','A','D','G'],'Gb':['B','E','A','D','G','C'],'Cb':['B','E','A','D','G','C','F']};
function frac(s,base){if(!s)return base;if(s==='/')return base/2;if(/^\/\d+$/.test(s))return base/Number(s.slice(1));if(/^\d+$/.test(s))return base*Number(s);const m=s.match(/^(\d*)\/(\d+)$/);return m?base*(Number(m[1]||1)/Number(m[2])):base}
function keyAcc(k){k=String(k||'C').trim().split(/\s+/)[0];const minor=/m$/.test(k);if(minor){const relative={Am:'C',Em:'G',Bm:'D','F#m':'A','C#m':'E','G#m':'B','D#m':'F#','A#m':'C#',Dm:'F',Gm:'Bb',Cm:'Eb',Fm:'Ab',Bbm:'Db',Ebm:'Gb',Abm:'Cb'};k=relative[k]||k.slice(0,-1)}const a=KEYS[k]||[];const flat=/b/.test(k)||['F','Bb','Eb','Ab','Db','Gb','Cb'].includes(k);return{set:new Set(a),flat}}
function pitch(tok,key,measureAcc){const m=tok.match(/^([\^_=]*)([A-Ga-g])([,']*)/);if(!m)return null;let[,acc,l,oct]=m,pc=SEMI[l.toUpperCase()],o=(l===l.toLowerCase()?5:4);for(const c of oct)o+=c==="'"?1:-1;let alter=0;if(acc){if(acc.includes('='))alter=0;else alter=(acc.match(/\^/g)||[]).length-(acc.match(/_/g)||[]).length;measureAcc[l.toUpperCase()]=alter}else if(Object.prototype.hasOwnProperty.call(measureAcc,l.toUpperCase()))alter=measureAcc[l.toUpperCase()];else if(key.set.has(l.toUpperCase()))alter=key.flat?-1:1;return 12*(o+1)+pc+alter}
const ABC_GM_PROGRAMS=[
 [/piano|klavier|pianoforte|grand/i,0],[/violin|violine|vln/i,40],[/viola|bratsche/i,41],[/violoncello|cello|vc\.?/i,42],[/contrabass|double bass|kontrabass/i,43],
 [/harp|harfe/i,46],[/flute|flöte|flauto/i,73],[/piccolo/i,72],[/oboe/i,68],[/english horn|cor anglais|englischhorn/i,69],[/clarinet|klarinette/i,71],[/bassoon|fagott/i,70],
 [/soprano sax/i,64],[/alto sax/i,65],[/tenor sax/i,66],[/baritone sax/i,67],[/trumpet|trompete/i,56],[/trombone|posaune/i,57],[/tuba/i,58],[/french horn|horn/i,60],
 [/acoustic guitar|gitarre|guitar/i,24],[/organ|orgel/i,19],[/accordion|akkordeon/i,21],[/choir|chor/i,52],[/voice|stimme|vocal/i,53]
];
function abcProgramForVoice(name){for(const [re,p] of ABC_GM_PROGRAMS)if(re.test(String(name||'')))return p;return 0}
function abcChannelForVoice(index,program){let ch=index%16;if(ch===9)ch=(ch+1)%16;return ch}
function parseABC(text){
 text=String(text||'').replace(/\r/g,'');const tuneStarts=[];for(const m of text.matchAll(/^X:\s*[^\n]+/gm))tuneStarts.push(m.index);if(tuneStarts.length>1)text=text.slice(tuneStarts[0],tuneStarts[1]).trim();
 const lines=text.split('\n');let title='ABC Import',meter=[4,4],unit=1/8,bpm=120,keyName='C',curV='V1';const voices=new Map(),voiceNames=new Map(),voicePrograms=new Map();let body=[];
 const voiceExpressions=new Map();const ensure=v=>{if(!voices.has(v))voices.set(v,[]);if(!voiceExpressions.has(v))voiceExpressions.set(v,[])};const expr=(v,type,at,data={})=>{ensure(v);voiceExpressions.get(v).push({type,at:Number(at)||0,...data})};
 for(let raw of lines){let line=raw.replace(/%.*/,'').trim();if(!line)continue;let m;
  if((m=line.match(/^T:\s*(.*)/)))title=m[1].trim()||title;
  else if((m=line.match(/^M:\s*(\d+)\/(\d+)/)))meter=[+m[1],+m[2]];
  else if((m=line.match(/^L:\s*(\d+)\/(\d+)/)))unit=+m[1]/+m[2];
  else if((m=line.match(/^Q:.*?=(\d+(?:\.\d+)?)/)))bpm=+m[1];
  else if((m=line.match(/^K:\s*([^\s]+)/)))keyName=m[1];
  else if((m=line.match(/^V:\s*([^\s]+)(.*)/))){curV=m[1];const nm=m[2].match(/(?:name|nm)="([^"]+)"/);if(nm)voiceNames.set(curV,nm[1]);ensure(curV)}
  else if((m=line.match(/^%%MIDI\s+program\s+(\d+)/i))){voicePrograms.set(curV,Math.max(0,Math.min(127,+m[1])))}
  else if((m=line.match(/^%%MIDI\s+voice\s+([^\s]+).*?instrument\s*=\s*(\d+)/i))){voicePrograms.set(m[1],Math.max(0,Math.min(127,+m[2]-1)))}
  else if(/^[A-Za-z]:/.test(line)||/^%%/.test(line)){}
  else {const inline=line.match(/^\[V:([^\]]+)\]/);if(inline){curV=inline[1];ensure(curV)}body.push([curV,line])}
 }
 if(!voices.size)voices.set('V1',[]);
 const key=keyAcc(keyName),bar=(meter[0]*4/meter[1]),pos=new Map([...voices.keys()].map(v=>[v,0])),accs=new Map([...voices.keys()].map(v=>[v,{}])),dynamics=new Map([...voices.keys()].map(v=>[v,78])),hairpins=new Map(),articulation=new Map(),slurDepth=new Map([...voices.keys()].map(v=>[v,0]));
 const dynLevel={ppp:28,pp:38,p:50,mp:62,mf:78,f:94,ff:110,fff:122,fp:92,sfz:118,ffz:122};
 const setHair=(v,dir)=>hairpins.set(v,dir);const endHair=v=>hairpins.delete(v);
 const noteVelocity=v=>{let x=dynamics.get(v)??78,dir=hairpins.get(v)||0;if(dir){x=Math.max(28,Math.min(122,x+dir*3));dynamics.set(v,x)}return x};
 const performedDuration=(v,d)=>{const a=articulation.get(v);articulation.delete(v);if(a==='staccato')return d*.55;if(a==='staccatissimo')return d*.35;if(a==='tenuto')return d*.95;if((slurDepth.get(v)||0)>0)return d*1.03;return d};
 for(const [defaultV,line0] of body){let v=defaultV||curV;ensure(v);if(!pos.has(v)){pos.set(v,0);accs.set(v,{});dynamics.set(v,78);slurDepth.set(v,0)}let i=0,line=line0;
  while(i<line.length){
   if(/\s/.test(line[i])){i++;continue}
   if(line[i]==='"'){const e=line.indexOf('"',i+1);i=e>=0?e+1:line.length;continue}
   const iv=line.slice(i).match(/^\[V:([^\]]+)\]/);if(iv){v=iv[1];ensure(v);if(!pos.has(v)){pos.set(v,0);accs.set(v,{});dynamics.set(v,78);slurDepth.set(v,0)}i+=iv[0].length;continue}
   const decoration=line.slice(i).match(/^([!+])([^!+]*?)\1/);if(decoration){let d=decoration[2].toLowerCase().trim();if(Object.prototype.hasOwnProperty.call(dynLevel,d)){dynamics.set(v,dynLevel[d]);expr(v,'dynamic',pos.get(v),{mark:d,value:dynLevel[d]})}else if(/^(?:crescendo|cresc\.?|<)\($/.test(d)){setHair(v,1);expr(v,'hairpin',pos.get(v),{direction:'crescendo',phase:'start'})}else if(/^(?:diminuendo|dim\.?|decresc\.?|>)\($/.test(d)){setHair(v,-1);expr(v,'hairpin',pos.get(v),{direction:'diminuendo',phase:'start'})}else if(/[<>]\)$/.test(d)||/^(?:crescendo|cresc\.?|diminuendo|dim\.?|decresc\.?)\)$/.test(d)){endHair(v);expr(v,'hairpin',pos.get(v),{phase:'stop'})}else if(/^(?:accent|marcato|sf|sforzando)$/.test(d)){articulation.set(v,'accent');expr(v,'articulation',pos.get(v),{kind:d})}else if(/^staccatissimo$/.test(d)){articulation.set(v,'staccatissimo');expr(v,'articulation',pos.get(v),{kind:d})}else if(/^staccato$/.test(d)){articulation.set(v,'staccato');expr(v,'articulation',pos.get(v),{kind:d})}else if(/^tenuto$/.test(d)){articulation.set(v,'tenuto');expr(v,'articulation',pos.get(v),{kind:d})}else if(/^(?:trill|trill\(|mordent|uppermordent|lowermordent|turn|invertedturn)$/.test(d)){expr(v,'ornament',pos.get(v),{kind:d.replace(/\($/,'')})}else if(/^(?:fermata|hold)$/.test(d)){expr(v,'fermata',pos.get(v),{})}else{expr(v,'direction',pos.get(v),{text:d})}i+=decoration[0].length;continue}
   if(line[i]==='('){slurDepth.set(v,(slurDepth.get(v)||0)+1);expr(v,'slur',pos.get(v),{phase:'start'});i++;continue}if(line[i]===')'){slurDepth.set(v,Math.max(0,(slurDepth.get(v)||0)-1));expr(v,'slur',pos.get(v),{phase:'stop'});i++;continue}
   if(line[i]==='.'&&/^[\^_=]*[A-Ga-g]/.test(line.slice(i+1))){articulation.set(v,'staccato');expr(v,'articulation',pos.get(v),{kind:'staccato'});i++;continue}if(line[i]==='{'){const e=line.indexOf('}',i+1);if(e>i){const toks=line.slice(i+1,e).match(/[\^_=]*[A-Ga-g][,']*/g)||[];const pitches=toks.map(t=>pitch(t,key,accs.get(v))).filter(Number.isFinite);expr(v,'grace',pos.get(v),{pitches});i=e+1;continue}}
   if(line[i]==='|'){accs.set(v,{});i++;while(i<line.length&&/[:|\[\]]/.test(line[i]))i++;continue}
   const rest=line.slice(i).match(/^[zx](\d*\/\d+|\/\d+|\/|\d+)?/);if(rest){pos.set(v,pos.get(v)+frac(rest[1],unit*4));i+=rest[0].length;continue}
   if(line[i]==='['&&!/^\[V:/.test(line.slice(i))){const end=line.indexOf(']',i);if(end>i){const inside=line.slice(i+1,end),lm=line.slice(end+1).match(/^(\d*\/\d+|\/\d+|\/|\d+)?/),d=frac(lm?.[1],unit*4),tokens=inside.match(/[\^_=]*[A-Ga-g][,']*/g)||[],vel=noteVelocity(v),pd=performedDuration(v,d);for(const t of tokens){const p=pitch(t,key,accs.get(v));if(p!=null)voices.get(v).push([pos.get(v),pd,p,articulation.get(v)==='accent'?Math.min(127,vel+20):vel])}pos.set(v,pos.get(v)+d);i=end+1+(lm?.[0]?.length||0);continue}}
   const n=line.slice(i).match(/^([\^_=]*[A-Ga-g][,']*)(\d*\/\d+|\/\d+|\/|\d+)?/);if(n){const d=frac(n[2],unit*4),p=pitch(n[1],key,accs.get(v)),baseVel=noteVelocity(v),a=articulation.get(v),vel=a==='accent'?Math.min(127,baseVel+20):baseVel,pd=performedDuration(v,d);if(p!=null)voices.get(v).push([pos.get(v),pd,p,vel]);pos.set(v,pos.get(v)+d);i+=n[0].length;continue}
   i++
  }
 }
 const tracks=[...voices.entries()].map(([id,notes],i)=>{const name=voiceNames.get(id)||id,program=voicePrograms.has(id)?voicePrograms.get(id):abcProgramForVoice(name);return{name,program,channel:abcChannelForVoice(i,program),notes,expressions:voiceExpressions.get(id)||[]}}).filter(t=>t.notes.length);
 if(!tracks.length)throw new Error('Keine unterstützten ABC-Noten gefunden.');
 return{title,bpm,timeSignature:meter,tracks,abcSource:text,importedFrom:'ABC',barCount:Math.max(1,Math.ceil(Math.max(...tracks.flatMap(t=>t.notes.map(n=>n[0]+n[1])))/bar))}
}
function parseCompositionRepresentation(text,representation){
 let raw=String(text||'').trim(),r=representationOf({representation});
 if(r==='free'){
  const pkg=raw.match(/^FORMAT\|LILYPOND\+MIDI\s*\nLILYPOND\s*\n([\s\S]*?)\nMIDI\s*\n([\s\S]+)$/i);
  if(pkg){
    const lilypondSource=String(pkg[1]||'').trim().replace(/^\`\`\`(?:lilypond|ly)?\s*/i,'').replace(/\s*\`\`\`$/,'').trim();
    const midiSource=String(pkg[2]||'').trim().replace(/^\`\`\`(?:text|midi)?\s*/i,'').replace(/\s*\`\`\`$/,'').trim();
    if(!/^\\version\s+"/m.test(lilypondSource))throw new Error('LilyPond-Block ohne \\version.');
    const score=extractMidiPerformanceScore(midiSource);score.lilypondSource=lilypondSource;
    return{score,format:'lilypond+midi',raw,lilypondSource,midiSource};
  }
  const m=raw.match(/^FORMAT\|(COMPACT|ABC|MIDI)\s*\n?/i);if(!m)throw new Error('FREE-Ausgabe ohne gültiges technisches Formatpaket.');r=m[1].toLowerCase();raw=raw.slice(m[0].length).trim()
}
 if(r==='compact'){if(/^\s*H\|/.test(raw))return{score:extractCompactScore(raw),format:'compact',raw};const obj=extractJson(raw);return{score:findScore(obj),format:'compact-json',raw,obj}}
 if(r==='midi')return{score:extractMidiPerformanceScore(raw),format:'midi',raw};
 if(r==='abc'){return{score:parseABC(raw),format:'abc',raw}}
 throw new Error('Unbekannte Musikrepräsentation.');
}
function extractJson(text){let s=String(text||'').trim().replace(/^\`\`\`(?:json)?\s*/i,'').replace(/\s*\`\`\`$/,'').trim();const parse=x=>JSON.parse(normalizeJsonNumbers(x));try{return parse(s)}catch(_){const closed=closeCompleteScoreJson(s);if(closed)return parse(closed);const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a)return parse(s.slice(a,b+1));throw _}}
function findScore(o){
 if(o&&Array.isArray(o.v)&&Number.isFinite(Number(o.b))){const ts=Array.isArray(o.m)?o.m:[4,4],beats=(Number(ts[0])||4)*(4/(Number(ts[1])||4));return{title:String(o.t||''),bpm:Number(o.b),timeSignature:ts,tracks:o.v.map((v,i)=>({name:String(v?.[0]||('Track '+(i+1))),program:Number(v?.[1])||0,channel:Number.isFinite(Number(v?.[2]))?Number(v[2]):i,notes:(Array.isArray(v?.[3])?v[3]:[]).map(e=>{if(!Array.isArray(e)||e.length<5)throw new Error('Ungültiges kompaktes Notenereignis.');const bar=Number(e[0]),pos=Number(e[1]),du=Number(e[2]),pi=Number(e[3]),ve=Number(e[4]);if(!Number.isInteger(bar)||bar<1||!Number.isFinite(pos)||pos<0||!Number.isFinite(du)||du<=0||!Number.isInteger(pi)||pi<0||pi>127||!Number.isInteger(ve)||ve<1||ve>127)throw new Error('Ungültiges kompaktes Notenereignis.');return[(bar-1)*beats+pos,du,pi,ve,typeof e[5]==='string'?e[5]:undefined]})}))}}
 const s=o&&o.score&&Array.isArray(o.score.tracks)?o.score:o;if(!s||!Array.isArray(s.tracks)||!Number.isFinite(Number(s.bpm)))throw new Error('Kein gültiges Partitur-Objekt gefunden.');return s
}
function findIdea(o){if(!o||typeof o!=='object')return'';for(const k of['idea','kompositionsidee','description','beschreibung','concept'])if(typeof o[k]==='string'&&o[k].trim())return o[k].trim();return''}
async function sha256Text(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sha256Buffer(buf){const b=await crypto.subtle.digest('SHA-256',buf);return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function vlq(n){n=Math.max(0,Math.round(n));let b=[n&127];while((n>>=7))b.unshift((n&127)|128);return b}const strBytes=s=>[...new TextEncoder().encode(s)],u32=n=>[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255],u16=n=>[(n>>>8)&255,n&255],chunk=(t,d)=>[...strBytes(t),...u32(d.length),...d];
function buildMidi(score){const ppq=960,bpm=Math.max(20,Math.min(400,Number(score.bpm)||120)),ts=Array.isArray(score.timeSignature)?score.timeSignature:[4,4],tracks=[],meta=[];const mpqn=Math.round(60000000/bpm);meta.push({tick:0,bytes:[255,81,3,(mpqn>>16)&255,(mpqn>>8)&255,mpqn&255]},{tick:0,bytes:[255,88,4,Number(ts[0])||4,Math.max(0,Math.round(Math.log2(Number(ts[1])||4))),24,8]});for(const te of(score.tempoEvents||[])){if(!Array.isArray(te)||te.length<2)continue;const tick=Math.max(0,Math.round((Number(te[0])||0)*ppq)),tbpm=Math.max(20,Math.min(400,Number(te[1])||bpm)),tm=Math.round(60000000/tbpm);meta.push({tick,bytes:[255,81,3,(tm>>16)&255,(tm>>8)&255,tm&255]})}meta.sort((a,b)=>a.tick-b.tick);let last=0,md=[];for(const e of meta){md.push(...vlq(e.tick-last),...e.bytes);last=e.tick}md.push(0,255,47,0);tracks.push(chunk('MTrk',md));(score.tracks||[]).forEach((tr,ti)=>{const ch=Math.max(0,Math.min(15,Number.isFinite(Number(tr.channel))?Number(tr.channel):ti%16)),prog=Math.max(0,Math.min(127,Number(tr.program)||0)),ev=[];const name=strBytes(String(tr.name||`Track ${ti+1}`));ev.push({tick:0,p:0,b:[255,3,...vlq(name.length),...name]},{tick:0,p:1,b:[192|ch,prog]});for(const n of(tr.notes||[])){if(!Array.isArray(n)||n.length<4)continue;const st=Math.max(0,Number(n[0])||0),du=Math.max(.01,Number(n[1])||.25),pitch=Math.max(0,Math.min(127,Math.round(Number(n[2])||60))),vel=Math.max(1,Math.min(127,Math.round(Number(n[3])||80)));ev.push({tick:Math.round(st*ppq),p:2,b:[144|ch,pitch,vel]},{tick:Math.round((st+du)*ppq),p:1,b:[128|ch,pitch,0]})}for(const c of(tr.cc||[])){if(!Array.isArray(c)||c.length<3)continue;const st=Math.max(0,Number(c[0])||0),cc=Math.max(0,Math.min(127,Math.round(Number(c[1])||0))),value=Math.max(0,Math.min(127,Math.round(Number(c[2])||0)));ev.push({tick:Math.round(st*ppq),p:0,b:[176|ch,cc,value]})}for(const pb of(tr.pitchBend||[])){if(!Array.isArray(pb)||pb.length<2)continue;const st=Math.max(0,Number(pb[0])||0),v=Math.max(-8192,Math.min(8191,Math.round(Number(pb[1])||0)))+8192;ev.push({tick:Math.round(st*ppq),p:0,b:[224|ch,v&127,(v>>7)&127]})}ev.sort((a,b)=>a.tick-b.tick||a.p-b.p);let prev=0,d=[];for(const e of ev){d.push(...vlq(e.tick-prev),...e.b);prev=e.tick}d.push(0,255,47,0);tracks.push(chunk('MTrk',d))});return new Uint8Array([...chunk('MThd',[...u16(1),...u16(tracks.length),...u16(ppq)]),...tracks.flat()])}

function draftField(draft,label){const lines=String(draft||'').split(/\r?\n/);const prefix=String(label||'').toLowerCase()+':';for(const line of lines){const t=line.trim();if(t.toLowerCase().startsWith(prefix))return t.slice(prefix.length).trim()}return''}
function scoreBarCount(score){const ts=Array.isArray(score?.timeSignature)?score.timeSignature:[4,4],beats=(Number(ts[0])||4)*(4/(Number(ts[1])||4));let end=0;for(const tr of(score?.tracks||[]))for(const n of(tr.notes||[]))if(Array.isArray(n))end=Math.max(end,(Number(n[0])||0)+(Number(n[1])||0));return Math.max(1,Math.ceil(end/Math.max(.25,beats)))}
function providerName(p){return p==='anthropic'?'Anthropic / Claude':p==='google'?'Google / Gemini':p==='openai'?'OpenAI':String(p||'')}
function localDescription(draft){const lines=String(draft||'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean);const prose=lines.find(s=>!/^([#*\-]|Titel\s*:|Tonart\s*:|Tempo\s*:|Taktart\s*:|Form\s*:)/i.test(s)&&s.length>35);return String(prose||'').replace(/[*#]/g,'').slice(0,500).trim()}
function compositionProfile(snapshot,score,draft,description){const bpm=Number(score?.bpm)||null,key=String(score?.key||score?.keySignature||score?.tonality||draftField(draft,'Tonart')||'').trim(),tempo=String(score?.tempo||score?.tempoMarking||draftField(draft,'Tempo')||'').trim(),bars=scoreBarCount(score),provider=providerName(snapshot?.provider),model=String(snapshot?.model||'').trim();const fields=[bpm?bpm+' BPM':'',tempo,key,bars+' Takte',[provider,model].filter(Boolean).join(' · ')].filter(Boolean);return{bpm,tempo,key,barCount:bars,provider,model,description:String(description||'').trim(),text:fields.join(' · ')+'\n\n'+String(description||'').trim()}}
async function compose({snapshot,key,repeatOf=null,seriesId=null,runId,now,requestModel,usedTitles=[]}){
 const startedAt=now(),run={id:runId,testId:runId,schema:'composition-engine-2.7-diagnosis-v1',app:{name:'Composition Engine Client',version:ENGINE_VERSION},seriesId,startedAt,repeatOf,contextMode:'creative-technical-separation',input:{visibleTask:snapshot.visibleTask,provider:snapshot.provider,model:snapshot.model,representation:representationOf(snapshot)},compositionContract:REPRESENTATION_CONTRACTS[representationOf(snapshot)],events:[],aiCalls:[],requestSnapshot:structuredClone(snapshot)};
 const ev=(phase,data={})=>run.events.push({at:now(),phase,...data});
 ev('run_started',{note:'Kreative Komposition und technische Realisation sind strikt getrennt. Die komponierende Instanz erhält keinen technischen Ausgabeformatvertrag.'});
 const call=async(prompt,stage)=>requestModel({snapshot,key,promptText:prompt,stage,run,event:ev});
 const musicalComposition=String(await call(createPrompts(snapshot).composition,'musical_composition')||'').trim();
 if(!musicalComposition)throw new Error('Die musikalische Komposition ist leer.');
 run.musicalComposition=musicalComposition;ev('musical_composition_completed',{note:'Musikalische Fassung abgeschlossen, bevor ein technisches Zielformat eingeführt wird.'});
 let rawComposition=String(await call(createPrompts(snapshot,musicalComposition).realization,'technical_realization')||'').trim();
 if(!rawComposition)throw new Error('Die technische Realisation ist leer.');
 let score,obj=null,parsedFormat='';try{const parsed=parseCompositionRepresentation(rawComposition,representationOf(snapshot));score=parsed.score;obj=parsed.obj||null;parsedFormat=parsed.format}catch(e){
   run.composition=rawComposition;run.rawCompositionOnError=rawComposition;ev('composition_format_invalid',{message:e?.message||String(e),characters:rawComposition.length,rawComposition});
   throw new Error('Die technische Realisation der bereits komponierten Musik ist nicht vollständig lesbar: '+(e?.message||String(e)));
 }
 run.composition=rawComposition;run.parsedModelJson=obj;run.score=score;
 if(score?.lilypondSource)run.lilypondSource=score.lilypondSource;
 run.representation={requested:representationOf(snapshot),parsed:parsedFormat};ev('composition_realized',{changed:true,representation:parsedFormat,note:'Die zweite Instanz realisiert ausschließlich technisch; sie erhält ausdrücklich kein Mandat zur Neukomposition.'});
 const title=String(score?.title||'').trim(),allTitles=usedTitles.filter(Boolean);if(title&&allTitles.some(t=>String(t).toLocaleLowerCase('de-DE')===title.toLocaleLowerCase('de-DE'))){let nt=(await call(duplicateTitlePrompt(title,allTitles,rawComposition),'title_renaming')).trim().replace(/^Titel:\\s*/i,'').replace(/^['“”"]|['“”"]$/g,'').trim();if(!nt||allTitles.some(t=>String(t).toLocaleLowerCase('de-DE')===nt.toLocaleLowerCase('de-DE'))){let n=2;while(allTitles.some(t=>String(t).toLocaleLowerCase('de-DE')===(title+' ('+n+')').toLocaleLowerCase('de-DE')))n++;nt=title+' ('+n+')'}score.title=nt;ev('duplicate_title_replaced',{oldTitle:title,newTitle:nt})}
 const midiBytes=buildMidi(score),buf=midiBytes.buffer.slice(midiBytes.byteOffset,midiBytes.byteOffset+midiBytes.byteLength),midiHash=await sha256Buffer(buf);run.midi={bytes:midiBytes.byteLength,sha256:midiHash,note:'Deterministisch lokal direkt aus der kreativen Quellpartitur erzeugt; kein KI-Übersetzungsschritt.'};ev('midi_generated',{bytes:midiBytes.byteLength,sha256:midiHash});
 const analysisSource=score?.lilypondSource||((parsedFormat==='abc'||parsedFormat==='midi'||parsedFormat==='compact')?rawComposition:JSON.stringify(scoreToCompact(score)));
 let idea='';try{idea=String(await call(createPrompts(snapshot,analysisSource).compositionIdea,'composition_analysis_afterwards')||'').trim()}catch(e){ev('composition_analysis_failed',{message:e?.message||String(e)})}run.idea=idea;run.profile=compositionProfile(snapshot,score,'',idea);ev('composition_profile_created',{bpm:run.profile.bpm,tempo:run.profile.tempo,key:run.profile.key,barCount:run.profile.barCount,provider:run.profile.provider,model:run.profile.model});run.completedAt=now();run.status='ok';
 return{run,midiBytes};
}

window.CompositionEngine=Object.freeze({name:ENGINE_NAME,version:ENGINE_VERSION,representations:REPRESENTATION_CONTRACTS,compose,analyzeScore,analyzeImprovement,improveScore,COMPOSITION_CONTRACT,TECHNICAL_CONTRACT,createPrompts,criticalAnalysisPrompt,postImprovementAnalysisPrompt,approvedImprovementPrompt,scoreToCompact,exportABC,exportLilyPond,exportMusicXML,playbackScore,performanceSnapshot,expressionAudit,mergeTitleRegistry,duplicateTitlePrompt,makeRequest,actualRequest,extractText,extractJson,findScore,findIdea,sha256Text,sha256Buffer,buildMidi,parseABC,extractCompactScore,extractMidiPerformanceScore,parseCompositionRepresentation});
})();
