(()=>{'use strict';

const ENGINE_NAME='Composition Engine';
const ENGINE_VERSION='2.5.1';

const TECHNICAL_CONTRACT=`TECHNISCHES FORMAT (kompakt):\nNur valides JSON.\n{\"t\":\"Titel\",\"b\":BPM,\"m\":[Z,N],\"v\":[[\"Instrument\",Program,Channel,[[Takt,Position,Dauer,Pitch,Velocity,"Notenname?"],...]],...]}\nTakt beginnt bei 1, Position bei 0. Pausen durch Lücken. Jede klingende Note der fertigen Komposition genau einmal ausgeben. Optionaler Notenname bewahrt die beabsichtigte Schreibweise (z. B. Db4/C#4). Keine musikalischen Änderungen.`;
function createPrompts(snapshot,draft='',translated=''){
 return{
  composition:'Komponiere jetzt das verlangte Stück vollständig. Erzeuge die Musik selbst – keinen Entwurf, keinen Formplan, kein Konzept, keine Klangbeschreibung und keine Erläuterung darüber, wie das Stück später komponiert werden könnte. Triff die musikalischen Entscheidungen unmittelbar in der Komposition: konkrete Stimmen, Tonhöhen, Dauern, Rhythmus, Harmonik, Artikulation, Dynamik und Verlauf. Die Komposition muss so vollständig und eindeutig notiert sein, dass eine nachfolgende technische Instanz sie ohne eigene musikalische Entscheidungen lediglich übertragen kann. Gib der fertigen Komposition einen kurzen Werktitel und, soweit musikalisch bestimmbar, Tonart und Tempo an. Denke nicht an MIDI-Codierung, QN-Werte, CS-Zeilen oder das technische Zielformat. Keine Analyse und keine Beschreibung der Arbeitsweise.\n\nAUFTRAG:\n'+snapshot.visibleTask,
  midiTranslation:'Übertrage die fertige Komposition vollständig und unverändert in das technische Format. Keine Analyse, keine Erklärung, keine Neukomposition.\\n\\n'+draft+'\\n\\n'+TECHNICAL_CONTRACT,
  compositionIdea:'Beschreibe die bereits fertig komponierte Komposition konkret, differenziert und hörbezogen. Erfasse, soweit in dieser Komposition tatsächlich erkennbar: Charakter und musikalische Grundidee, melodische Gestaltung, Rhythmik, Harmonik/Tonalität, Verhältnis der Stimmen bzw. Instrumente, formale Entwicklung sowie besonders charakteristische Wendungen oder Kontraste. Benenne konkrete musikalische Eigenschaften statt allgemeiner Floskeln. Etwa 800 bis 1500 Zeichen, höchstens 1500 Zeichen. Keine Takt-für-Takt-Analyse, keine Überschriften, keine Bewertung, keine Verbesserungsvorschläge, keine technischen MIDI-Metadaten und keine Wiederholung des Auftrags. Erfinde nichts; die Beschreibung muss ausschließlich aus der fertigen Komposition abgeleitet sein.\\n\\nFERTIGE KOMPOSITION:\\n'+draft
 };
}
function criticalAnalysisPrompt(score){return 'Beurteile die folgende Partitur zuerst als zeitlichen Hörverlauf, nicht als theoretische Konstruktion. Oberste Priorität hat musikalischer Fluss: Suche systematisch nach ungewolltem Stolpern, Minipausen, Löchern zwischen aufeinanderfolgenden Tönen/Akkorden, zu kurzen Dauern, fehlender Bindung, abgehackter Phrasierung, mechanischen Neustarts und unnatürlichen Notenenden. Prüfe dazu ausdrücklich Startzeit und Dauer benachbarter Ereignisse in jeder Stimme und unterscheide beabsichtigte Pausen von wahrscheinlich unbeabsichtigten Lücken. Erst danach beurteile Wiederholungen, Begleitmuster, Rhythmik, Harmonik, Form, Register, Dynamik und Spannungsverlauf. Ein formal korrektes Stück ist nicht gelungen, wenn sein hörbarer Fluss grundlegend gestört ist. Beginne zwingend mit genau "URTEIL: ÄNDERN" oder "URTEIL: BEHALTEN". Danach höchstens 220 Zeichen: nenne nur die wichtigste hörbare Schwäche und eine knappe konkrete Korrektur. Bei ÄNDERN folgt ein kurzer konkreter Vorschlag, der die Ursachen in den Notenereignissen beseitigt. Keine Lobhudelei, keine Überschriften, keine Takt-für-Takt-Abhandlung.\\n\\nPARTITUR:\\n'+JSON.stringify(scoreToCompact(score))+'\\n\\nFORMAT:\\n'+TECHNICAL_CONTRACT}
function approvedImprovementPrompt(score,assessment){return 'Überarbeite die vorhandene Partitur musikalisch mit voller kompositorischer Sorgfalt. Beseitige die im freigegebenen Urteil diagnostizierten hörbaren Ursachen tatsächlich. Priorität haben Fluss und Phrasierung: ungewollte Minipausen, Lücken, zu kurze Dauern, fehlende Bindung, abgehackte Übergänge oder mechanisches Stolpern müssen in den konkreten Startzeiten und Dauern korrigiert werden, soweit sie nicht musikalisch beabsichtigt sind. Prüfe die geänderten Passagen als zusammenhängenden zeitlichen Verlauf. Bewahre überzeugende Eigenschaften und ändere nichts ohne musikalischen Grund. Antworte ausschließlich mit der vollständigen Partitur im kompakten JSON-Format.\\n\\nFREIGEGEBENES URTEIL:\\n'+String(assessment||'').trim()+'\\n\\nPARTITUR:\\n'+JSON.stringify(scoreToCompact(score))+'\\n\\nFORMAT:\\n'+TECHNICAL_CONTRACT}
function postImprovementAnalysisPrompt(improvedScore){return 'Beurteile diese Partitur unabhängig und ohne Kenntnis einer früheren Fassung. Behandle sie als aktuelle Originalfassung. Prüfe zuerst und systematisch den zeitlichen Hörfluss: ungewolltes Stolpern, Minipausen, Lücken zwischen Ereignissen, zu kurze Dauern, fehlende Bindung, abgehackte Phrasierung, mechanische Neustarts und unnatürliche Notenenden. Prüfe dafür Startzeit und Dauer benachbarter Ereignisse jeder Stimme. Erst danach beurteile Wiederholungen, Rhythmik, Harmonik, Form und Spannungsverlauf. Beginne genau mit "URTEIL: ÄNDERN" oder "URTEIL: BEHALTEN". Danach höchstens 220 Zeichen: nur der wichtigste konkrete Befund; bei ÄNDERN eine knappe umsetzbare Korrektur. Keine Lobhudelei, keine Überschriften.\\n\\nPARTITUR:\\n'+JSON.stringify(scoreToCompact(improvedScore))+'\\n\\nFORMAT:\\n'+TECHNICAL_CONTRACT}
function conciseAssessment(text){const raw=String(text||'').trim(),m=raw.match(/^\\s*URTEIL:\\s*(ÄNDERN|BEHALTEN)\\b/im),verdict=m?'URTEIL: '+m[1].toUpperCase():'URTEIL: ÄNDERN',rest=raw.replace(/^\\s*URTEIL:\\s*(?:ÄNDERN|BEHALTEN)\\b[:\\s-]*/i,'').replace(/\\s+/g,' ').trim();return verdict+(rest?'\\n'+rest.slice(0,220).trim():'')}
async function analyzeScore({score,snapshot,key,requestModel,run=null,event=null}){if(!score)throw new Error('Keine Partitur für die Analyse.');if(typeof requestModel!=='function')throw new Error('requestModel fehlt.');const promptText=criticalAnalysisPrompt(score),text=conciseAssessment(await requestModel({snapshot,key,promptText,stage:'critical_score_analysis',run,event}));return{assessment:text,unchanged:/^\\s*URTEIL:\\s*BEHALTEN\\b/im.test(text),promptText}}
async function analyzeImprovement({improvedScore,snapshot,key,requestModel,run=null,event=null}){if(!improvedScore)throw new Error('Verbesserungsfassung fehlt.');if(typeof requestModel!=='function')throw new Error('requestModel fehlt.');const promptText=postImprovementAnalysisPrompt(improvedScore),text=conciseAssessment(await requestModel({snapshot,key,promptText,stage:'post_improvement_analysis',run,event}));return{assessment:text,unchanged:/^\\s*URTEIL:\\s*BEHALTEN\\b/im.test(text),promptText}}
function scoreToCompact(score){const ts=Array.isArray(score?.timeSignature)?score.timeSignature:[4,4],beats=(Number(ts[0])||4)*(4/(Number(ts[1])||4));return{t:String(score?.title||''),b:Number(score?.bpm)||120,m:ts,v:(score?.tracks||[]).map((tr,i)=>[String(tr.name||('Track '+(i+1))),Number(tr.program)||0,Number.isFinite(Number(tr.channel))?Number(tr.channel):i,(tr.notes||[]).map(n=>{const start=Number(n?.[0])||0,bar=Math.floor(start/beats)+1,pos=start-(bar-1)*beats,row=[bar,pos,Number(n?.[1])||.25,Number(n?.[2])||60,Number(n?.[3])||80];if(typeof n?.[4]==='string'&&n[4])row.push(n[4]);return row})])}}
async function improveScore({score,assessment,snapshot,key,requestModel,run=null,event=null}){if(!score||!String(assessment||'').trim())throw new Error('Partitur oder Verbesserungsvorschlag fehlt.');if(typeof requestModel!=='function')throw new Error('requestModel fehlt.');const promptText=approvedImprovementPrompt(score,assessment),text=String(await requestModel({snapshot,key,promptText,stage:'approved_score_improvement',run,event})||'').trim(),obj=extractJson(text),improvedScore=findScore(obj);return{score:improvedScore,midiBytes:buildMidi(improvedScore),raw:text,promptText}}

function duplicateTitlePrompt(title,allTitles,draft){const hint=String(draft||'').slice(0,700);return'Erfinde ausschließlich einen neuen kurzen Werktitel für die bereits fertige Komposition. Keine musikalische Änderung. Antworte nur mit dem Titel.\n\nBISHERIGER TITEL:\n'+title+'\n\nBEREITS VERWENDET:\n'+allTitles.join('\n')+'\n\nKURZER KONTEXT:\n'+hint}
function makeRequest(p,m,promptText,stage){if(p==='openai')return{provider:p,model:m,url:'https://api.openai.com/v1/responses',method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer {{API_KEY}}'},body:{model:m,input:[{role:'user',content:[{type:'input_text',text:promptText}]}],store:false,...((stage.startsWith('midi_translation'))?{reasoning:{effort:'low'},max_output_tokens:16000}:{})}};if(p==='anthropic'){const body={model:m,max_tokens:32768,messages:[{role:'user',content:promptText}]};if(/^claude-(?:sonnet|opus)-5(?:$|-)/i.test(m)&&stage.startsWith('midi_translation')){body.thinking={type:'disabled'};body.max_tokens=32768}return{provider:p,model:m,url:'https://api.anthropic.com/v1/messages',method:'POST',headers:{'Content-Type':'application/json','x-api-key':'{{API_KEY}}','anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body};}const body={contents:[{role:'user',parts:[{text:promptText}]}]};if(/^gemini-3\./i.test(m)&&(stage.startsWith('midi_translation')||stage==='composition_idea_afterwards'))body.generationConfig={thinkingConfig:{thinkingLevel:'low'}};return{provider:p,model:m,url:`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(m)}:generateContent?key={{API_KEY}}`,method:'POST',headers:{'Content-Type':'application/json'},body}}
function actualRequest(s,key){const headers={...s.headers};let url=s.url;for(const k of Object.keys(headers)){if(typeof headers[k]==='string'&&headers[k].includes('{{API_KEY}}'))headers[k]=headers[k].replace('{{API_KEY}}',key)}url=url.replace('{{API_KEY}}',encodeURIComponent(key));return{url,headers,body:structuredClone(s.body)}}
function extractText(p,j){if(p==='openai'){if(typeof j.output_text==='string')return j.output_text;const parts=[];for(const item of(j.output||[]))for(const c of(item.content||[]))if(typeof c.text==='string')parts.push(c.text);return parts.join('\n')}if(p==='anthropic')return(j.content||[]).filter(x=>x.type==='text').map(x=>x.text||'').join('\n');return(j.candidates||[]).flatMap(c=>c.content?.parts||[]).map(p=>p.text||'').join('\n')}
function normalizeJsonNumbers(s){let out='',quoted=false,escaped=false;for(let i=0;i<s.length;i++){const c=s[i];if(quoted){out+=c;if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')quoted=false;continue}if(c==='"'){quoted=true;out+=c;continue}if(c==='.'&&/[0-9]/.test(s[i+1]||'')&&(/[\[:,\[]/.test(s.slice(0,i).trimEnd().slice(-1))||(/[\[:,\[]/.test(s.slice(0,i).trimEnd().slice(-2,-1))&&s[i-1]==='-'))){out+='0'+c;continue}out+=c}return out}
function closeCompleteScoreJson(s){if(!s.endsWith('}'))return null;let stack=[],quoted=false,escaped=false;for(let i=0;i<s.length;i++){const c=s[i];if(quoted){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')quoted=false;continue}if(c==='"'){quoted=true;continue}if(c==='{'||c==='['){stack.push(c);continue}if(c==='}'||c===']'){const top=stack[stack.length-1];if((top==='{'&&c==='}')||(top==='['&&c===']')){stack.pop();continue}if(i===s.length-1&&c==='}'&&top==='['&&stack[0]==='{'&&stack.slice(1).every(x=>x==='[')){const candidate=s.slice(0,-1)+']'.repeat(stack.length-1)+'}';try{const obj=JSON.parse(normalizeJsonNumbers(candidate));if(Array.isArray(obj.v)&&obj.v.length>0&&obj.v.every(v=>Array.isArray(v)&&Array.isArray(v[3])&&v[3].length>0))return candidate}catch(_){} }return null}}return null}
function extractJson(text){let s=String(text||'').trim().replace(/^\`\`\`(?:json)?\s*/i,'').replace(/\s*\`\`\`$/,'').trim();const parse=x=>JSON.parse(normalizeJsonNumbers(x));try{return parse(s)}catch(_){const closed=closeCompleteScoreJson(s);if(closed)return parse(closed);const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a)return parse(s.slice(a,b+1));throw _}}
function findScore(o){
 if(o&&Array.isArray(o.v)&&Number.isFinite(Number(o.b))){const ts=Array.isArray(o.m)?o.m:[4,4],beats=(Number(ts[0])||4)*(4/(Number(ts[1])||4));return{title:String(o.t||''),bpm:Number(o.b),timeSignature:ts,tracks:o.v.map((v,i)=>({name:String(v?.[0]||('Track '+(i+1))),program:Number(v?.[1])||0,channel:Number.isFinite(Number(v?.[2]))?Number(v[2]):i,notes:(Array.isArray(v?.[3])?v[3]:[]).map(e=>{if(!Array.isArray(e)||e.length<5)throw new Error('Ungültiges kompaktes Notenereignis.');const bar=Number(e[0]),pos=Number(e[1]),du=Number(e[2]),pi=Number(e[3]),ve=Number(e[4]);if(!Number.isInteger(bar)||bar<1||!Number.isFinite(pos)||pos<0||!Number.isFinite(du)||du<=0||!Number.isInteger(pi)||pi<0||pi>127||!Number.isInteger(ve)||ve<1||ve>127)throw new Error('Ungültiges kompaktes Notenereignis.');return[(bar-1)*beats+pos,du,pi,ve,typeof e[5]==='string'?e[5]:undefined]})}))}}
 const s=o&&o.score&&Array.isArray(o.score.tracks)?o.score:o;if(!s||!Array.isArray(s.tracks)||!Number.isFinite(Number(s.bpm)))throw new Error('Kein gültiges Partitur-Objekt gefunden.');return s
}
function findIdea(o){if(!o||typeof o!=='object')return'';for(const k of['idea','kompositionsidee','description','beschreibung','concept'])if(typeof o[k]==='string'&&o[k].trim())return o[k].trim();return''}
async function sha256Text(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sha256Buffer(buf){const b=await crypto.subtle.digest('SHA-256',buf);return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function vlq(n){n=Math.max(0,Math.round(n));let b=[n&127];while((n>>=7))b.unshift((n&127)|128);return b}const strBytes=s=>[...new TextEncoder().encode(s)],u32=n=>[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255],u16=n=>[(n>>>8)&255,n&255],chunk=(t,d)=>[...strBytes(t),...u32(d.length),...d];
function buildMidi(score){const ppq=480,bpm=Math.max(20,Math.min(400,Number(score.bpm)||120)),ts=Array.isArray(score.timeSignature)?score.timeSignature:[4,4],tracks=[],meta=[];const mpqn=Math.round(60000000/bpm);meta.push({tick:0,bytes:[255,81,3,(mpqn>>16)&255,(mpqn>>8)&255,mpqn&255]},{tick:0,bytes:[255,88,4,Number(ts[0])||4,Math.max(0,Math.round(Math.log2(Number(ts[1])||4))),24,8]});let last=0,md=[];for(const e of meta){md.push(...vlq(e.tick-last),...e.bytes);last=e.tick}md.push(0,255,47,0);tracks.push(chunk('MTrk',md));(score.tracks||[]).forEach((tr,ti)=>{const ch=Math.max(0,Math.min(15,Number.isFinite(Number(tr.channel))?Number(tr.channel):ti%16)),prog=Math.max(0,Math.min(127,Number(tr.program)||0)),ev=[];const name=strBytes(String(tr.name||`Track ${ti+1}`));ev.push({tick:0,p:0,b:[255,3,...vlq(name.length),...name]},{tick:0,p:1,b:[192|ch,prog]});for(const n of(tr.notes||[])){if(!Array.isArray(n)||n.length<4)continue;const st=Math.max(0,Number(n[0])||0),du=Math.max(.01,Number(n[1])||.25),pitch=Math.max(0,Math.min(127,Math.round(Number(n[2])||60))),vel=Math.max(1,Math.min(127,Math.round(Number(n[3])||80)));ev.push({tick:Math.round(st*ppq),p:2,b:[144|ch,pitch,vel]},{tick:Math.round((st+du)*ppq),p:1,b:[128|ch,pitch,0]})}ev.sort((a,b)=>a.tick-b.tick||a.p-b.p);let prev=0,d=[];for(const e of ev){d.push(...vlq(e.tick-prev),...e.b);prev=e.tick}d.push(0,255,47,0);tracks.push(chunk('MTrk',d))});return new Uint8Array([...chunk('MThd',[...u16(1),...u16(tracks.length),...u16(ppq)]),...tracks.flat()])}

function draftField(draft,label){const lines=String(draft||'').split(/\r?\n/);const prefix=String(label||'').toLowerCase()+':';for(const line of lines){const t=line.trim();if(t.toLowerCase().startsWith(prefix))return t.slice(prefix.length).trim()}return''}
function scoreBarCount(score){const ts=Array.isArray(score?.timeSignature)?score.timeSignature:[4,4],beats=(Number(ts[0])||4)*(4/(Number(ts[1])||4));let end=0;for(const tr of(score?.tracks||[]))for(const n of(tr.notes||[]))if(Array.isArray(n))end=Math.max(end,(Number(n[0])||0)+(Number(n[1])||0));return Math.max(1,Math.ceil(end/Math.max(.25,beats)))}
function providerName(p){return p==='anthropic'?'Anthropic / Claude':p==='google'?'Google / Gemini':p==='openai'?'OpenAI':String(p||'')}
function localDescription(draft){const lines=String(draft||'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean);const prose=lines.find(s=>!/^([#*\-]|Titel\s*:|Tonart\s*:|Tempo\s*:|Taktart\s*:|Form\s*:)/i.test(s)&&s.length>35);return String(prose||'').replace(/[*#]/g,'').slice(0,500).trim()}
function compositionProfile(snapshot,score,draft,description){const bpm=Number(score?.bpm)||null,key=String(score?.key||score?.keySignature||score?.tonality||draftField(draft,'Tonart')||'').trim(),tempo=String(score?.tempo||score?.tempoMarking||draftField(draft,'Tempo')||'').trim(),bars=scoreBarCount(score),provider=providerName(snapshot?.provider),model=String(snapshot?.model||'').trim();const fields=[bpm?bpm+' BPM':'',tempo,key,bars+' Takte',[provider,model].filter(Boolean).join(' · ')].filter(Boolean);return{bpm,tempo,key,barCount:bars,provider,model,description:String(description||'').trim(),text:fields.join(' · ')+'\n\n'+String(description||'').trim()}}
async function compose({snapshot,key,repeatOf=null,seriesId=null,runId,now,requestModel,usedTitles=[]}){
 const startedAt=now(),run={id:runId,testId:runId,schema:'minimal-composer-diagnosis-v3',app:{name:'Composition Engine Client',version:ENGINE_VERSION},seriesId,startedAt,repeatOf,contextMode:'isolated-two-stage',input:{visibleTask:snapshot.visibleTask,provider:snapshot.provider,model:snapshot.model},technicalContract:TECHNICAL_CONTRACT,events:[],aiCalls:[],requestSnapshot:structuredClone(snapshot)};
 const ev=(phase,data={})=>run.events.push({at:now(),phase,...data});
 ev('run_started',{note:'Keine frühere Unterhaltung oder Komposition wird an das Modell übertragen.'});
 const call=async(prompt,stage)=>requestModel({snapshot,key,promptText:prompt,stage,run,event:ev});
 const draft=await call(createPrompts(snapshot).composition,'composition');if(!draft.trim())throw new Error('Die Komposition ist leer.');run.composition=draft;
 let translated=await call(createPrompts(snapshot,draft).midiTranslation,'midi_translation');
 const validJson=s=>{try{extractJson(s);return true}catch{return false}};
 if(!validJson(translated)){
   ev('midi_translation_incomplete',{characters:translated.length,note:'Technische JSON-Übertragung unvollständig; die fertige Komposition bleibt unverändert.'});
   for(let attempt=0;attempt<2&&!validJson(translated);attempt++){
     const tail=translated.slice(-2400);
     const continuation='Die technische JSON-Übertragung wurde bei der Ausgabe abgeschnitten. Setze exakt an der Abbruchstelle fort. Keine Wiederholung, keine Einleitung, keine neuen Noten und keine musikalischen Änderungen. Antworte ausschließlich mit dem unmittelbar anschließenden JSON-Text bis zum Abschluss. Letzte Zeichen der bisherigen Ausgabe:\\n'+tail;
     let addition=String(await call(continuation,'midi_translation_continuation_'+(attempt+1))||'').trim().replace(/^\`\`\`(?:json)?\\s*/i,'').replace(/\\s*\`\`\`$/,'');
     const overlap=Math.min(translated.length,addition.length,1200);let matched=0;
     for(let n=overlap;n>0;n--)if(translated.endsWith(addition.slice(0,n))){matched=n;break}
     translated+=addition.slice(matched);
     ev('midi_translation_continued',{attempt:attempt+1,addedCharacters:addition.length-matched,totalCharacters:translated.length});
   }
 }
 if(!validJson(translated))throw new Error('Technische Partiturausgabe auch nach zwei Fortsetzungen unvollständig. Die fertige Komposition wurde nicht verändert.');
 const obj=extractJson(translated);run.parsedModelJson=obj;ev('model_json_parsed',{stage:'midi_translation',changed:false,note:'Nur JSON geparst; keine musikalische Korrektur.'});const score=findScore(obj);run.score=score;
 const title=String(score?.title||'').trim(),allTitles=usedTitles.filter(Boolean);if(title&&allTitles.some(t=>String(t).toLocaleLowerCase('de-DE')===title.toLocaleLowerCase('de-DE'))){let nt=(await call(duplicateTitlePrompt(title,allTitles,draft),'title_renaming')).trim().replace(/^Titel:\s*/i,'').replace(/^['“”"]|['“”"]$/g,'').trim();if(!nt||allTitles.some(t=>String(t).toLocaleLowerCase('de-DE')===nt.toLocaleLowerCase('de-DE')))nt=title+' '+new Date().toLocaleDateString('de-DE');score.title=nt;ev('duplicate_title_replaced',{oldTitle:title,newTitle:nt})}
 const midiBytes=buildMidi(score),buf=midiBytes.buffer.slice(midiBytes.byteOffset,midiBytes.byteOffset+midiBytes.byteLength),midiHash=await sha256Buffer(buf);run.midi={bytes:midiBytes.byteLength,sha256:midiHash,note:'Deterministisch lokal aus den unveränderten Partiturwerten erzeugt; keine musikalische Nachbearbeitung.'};ev('midi_generated',{bytes:midiBytes.byteLength,sha256:midiHash});
 let idea='';try{idea=String(await call(createPrompts(snapshot,draft).compositionIdea,'composition_analysis_afterwards')||'').trim()}catch(e){ev('composition_analysis_failed',{message:e?.message||String(e)})}if(!idea)idea=localDescription(draft);run.idea=idea;ev(idea===localDescription(draft)?'composition_description_fallback_local':'composition_analysis_created',{characters:idea.length});run.profile=compositionProfile(snapshot,score,draft,run.idea);ev('composition_profile_created',{bpm:run.profile.bpm,tempo:run.profile.tempo,key:run.profile.key,barCount:run.profile.barCount,provider:run.profile.provider,model:run.profile.model});run.completedAt=now();run.status='ok';
 return{run,midiBytes};
}

window.CompositionEngine=Object.freeze({name:ENGINE_NAME,version:ENGINE_VERSION,compose,analyzeScore,analyzeImprovement,improveScore,TECHNICAL_CONTRACT,createPrompts,criticalAnalysisPrompt,postImprovementAnalysisPrompt,approvedImprovementPrompt,scoreToCompact,duplicateTitlePrompt,makeRequest,actualRequest,extractText,extractJson,findScore,findIdea,sha256Text,sha256Buffer,buildMidi});
})();
